name: Sync to Client Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git
        run: |
          git config user.name "Rocket Dev Sync Bot"
          git config user.email "dev@rocketdevelopers.com"
          
      - name: Push to client repository
        env:
          CLIENT_REPO_TOKEN: ${{ secrets.CLIENT_REPO_TOKEN }}
        run: |
          git remote add client https://x-access-token:${CLIENT_REPO_TOKEN}@github.com/liftronic/liftronic-elevator.git
          git push client main:main --force